controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

get_currencies:
  path: /api/currencies
  controller: App\Controller\CurrencyController::getCurrencies
  methods: [GET]

get_currency:
  path: /api/currencies/{id}
  controller: App\Controller\CurrencyController::getCurrency
  methods: [GET]

api_currencies_create:
  path: /api/currencies
  controller: App\Controller\CurrencyController::addCurrency
  methods: [POST]
