controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_currencies:
  path: /api/currencies
  controller: App\Controller\CurrencyController::getCurrencies
  methods: [GET]

api_currencies_create:
  path: /api/currencies
  controller: App\Controller\CurrencyController::addCurrency
  methods: [POST]
