controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_currency:
  path: /api/currencies
  controller: App\Controller\Api\CurrencyController

api_currency_exchange:
  path: /api/currencies/exchange
  controller: App\Controller\Api\CurrencyExchangeController
